# Generated by Django 3.2 on 2021-07-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='bike_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
