# Generated by Django 3.2 on 2021-07-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_zone', '0003_bikes_bike_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='bike_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
