# Generated by Django 3.2 on 2021-07-25 13:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_zone', '0005_bikes_bike_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='bike_description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
