# Generated by Django 3.2 on 2021-07-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_zone', '0008_bikes_bike_engine_displacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='bike_max_power',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
