# Generated by Django 3.2 on 2021-07-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_zone', '0014_bikes_bike_valve_per_cylinder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='bike_fuel_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
