# Generated by Django 3.2 on 2021-07-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_zone', '0017_bikes_bike_ignition'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='bike_is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikes',
            name='bike_is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
